---
esphome:
  name: thermostat-dial-debug
  friendly_name: Thermostat Debug
  platformio_options:
    build_flags:
      - -DDEBUG_TEST

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

api:

logger:
  level: DEBUG

wifi:
  ssid: "YOUR_WIFI_SSID"
  password: "YOUR_WIFI_PASSWORD"
  enable_on_boot: false

ota:
  - platform: esphome

spi:
  mosi_pin: GPIO5
  clk_pin: GPIO6

display:
  - platform: ili9xxx
    id: m5dial_display
    model: GC9A01A
    cs_pin: GPIO7
    dc_pin: GPIO4
    reset_pin: GPIO8
    invert_colors: true
    update_interval: never

external_components:
  - source:
      type: local
      path: components

m5dial_thermostat:
  entity_id: climate.my_thermostat
  display_id: m5dial_display
  active_brightness: 255
  idle_brightness: 50
  idle_timeout: 30s
  enable_sounds: true
  comms_timeout: 30s
